#!/bin/bash
# Author: Carlos Antón
# Date: 10/05/2021
# Description: script that names files 1,2,3.. following a order by date of created of the file
# Date Modified: 10/05/2021

#x=$(ls -ltr /home/carlos/carpeta_prueba/folder | awk '{print $9}')   #guardamos en variable el out del comando (su columna 9)

#for i in $x
#do
#echo $i
#done

x=$(ls -ltr /home/carlos/carpeta_prueba/folder | awk '{print $9}')   #guardamos en variable el out del comando (su columna 9)

num=1
for i in $x
do
mv /home/carlos/carpeta_prueba/folder/$i /home/carlos/carpeta_prueba/folder/$num
num=$((num+1))
done
