#!/bin/bash
# Author: Carlos Antón
# Date: 10/05/2021
# Description: script that names files 1,2,3.. following a order by date of created of the file
# Date Modified: 10/05/2021

#x=$(ls -ltr /home/carlos/carpeta_prueba/folder | awk '{print $9}')   #guardamos en variable el out del comando (su columna 9)

#for i in $x
#do
#echo $i
#done

echo "Introduce the absolute path of the folder: "
read absolute_path
if [ -e $absolute_path ]
then
  x=$(ls -ltr $absolute_path | awk '{print $9}')   #guardamos en variable los nombres de los archivos(columna 9)
  num=1
  for i in $x
  do
  mv $absolute_path/$i $absolute_path/$num
  num=$((num+1))
  done
else
  echo File does not exist
fi


